#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" > /usr/share/nginx/html/index.html

