#!/usr/bin/env bash
# Install nginx web server
# Another comment
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chmod o+w /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
