#!/usr/bin/env bash
# Install MySQL

echo 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7-dmr' | sudo tee -a /etc/apt/sources.list
# apt-get update
sudo apt-get -y update
# install MySQL 5.7
sudo apt-get -y install mysql-server-5.7
# Show MySQL version
mysql --version
# Start MySQL
sudo service mysql restart
