#!/usr/bin/env bash

# Create new user replica_user
echo "Enter root password"
mysql -uroot -p -e "CREATE USER 'replica_user'@'%' IDENTIFIED BY 'root';
GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';
GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost'"
