#!/usr/bin/env bash
# Bash script that:
echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command' && rm '/var/run/holbertonscript.pid'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
while :
do
	echo "To infinity and beyond"
done

