#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
filename="testfile"
while read -r line
do
	USERNAME=($line)
	echo "$USERNAME"
done < $filename
