#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
filename="testfile"
while IFS":" read USERNAME GROUP_ID HOME_DIRECTORY COMMAND/SHELL
do
	USERNAME=($line)
	echo "$USERNAME"
done < $filename
