#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/file
sed -i 's/127.0.0.1/127.0.0.2/g' ~/file
echo "8.8.8.8   facebook.com" >> ~/file
cp -f ~/file /etc/hosts
